apache/rocketmq-clients

docs/message_id.md
java/README.md

Docs: add example for java client

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/MessageMeter.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/MessageMeterProvider.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/Metric.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/MetricMessageInterceptor.java

Java: refactor MessageMeter

---

.github/workflows/license_checker.yml
.licenserc.json

Support license checker

---

java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncProducerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncSimpleConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerDelayMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerFifoMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerNormalMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerTransactionMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/PushConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

1. replace the endpoints port with 8080
2. indicate that the credential provider is optional

Polish the java example

---

java/client-shade/src/main/resources/rocketmq.logback.xml
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/resources/logback.xml

Fixes https://github.com/grpc/grpc-java/issues/7351

Reduce the telemetry timeout to avoid the bug in JDK8 + macOS

---

cpp/source/concurrent/tests/BUILD.bazel
cpp/source/concurrent/tests/CountdownLatchTest.cpp
cpp/source/rocketmq/ClientImpl.cpp
cpp/source/rocketmq/include/ClientImpl.h
cpp/source/rocketmq/tests/BUILD.bazel
cpp/source/rocketmq/tests/ClientImplTest.cpp

Follow: Effective C++ Item 23 Prefer non-member non-friend functions to member functions

Make clientId() a free function

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java

fix bug in changeInvisibleDuration

fix bug in changeInvisibleDuration

---

.asf.yaml

Enhance the mergeability: add misspell-check into contexts of the protected branch

Enhance the mergeability: add misspell-check into contexts of the protected branch

---

.asf.yaml

Enhance the mergeability: add check-license into contexts of the protected branch

Enhance the mergeability: add check-license into contexts of the protected branch

---

.asf.yaml

Reverts apache/rocketmq-clients#172

Revert "Remove protected branch"

---

java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml

Exclude annotation-apis from the shaded jar

---

golang/client.go
golang/client_manager.go
golang/conn.go
golang/consumer.go
golang/error.go
golang/example/consumer/simple_consumer/main.go
golang/example/producer/async/main.go
golang/example/producer/delay/main.go
golang/example/producer/fifo/main.go
golang/example/producer/normal/main.go
golang/example/producer/transaction/main.go
golang/log.go
golang/message.go
golang/metric.go
golang/pkg/utils/utils.go
golang/producer.go
golang/publishing_message.go
golang/rpc_client.go
golang/simple_consumer.go
golang/simple_consumer_options.go
golang/transaction.go

No longer distinguish between producerName and consumerGroup, unified as groupName

change 'consumerGroup' to 'groupName'

---

java/client-apis/pom.xml
java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml

Release rocketmq-client-java 5.0.1

---

docs/design.md

Add docs about client id

---

docs/design.md
docs/observability.md

Initial commit of observability docs

---

golang/client.go
golang/pkg/utils/utils.go
golang/producer.go
golang/producer_test.go
golang/simple_consumer.go

log error with requestId

---

java/style/copyright/Apache.xml

close #233 
- Add copyright xml file for java client

[ISSUE #233]Add copyright xml file for java client

---

java/client-apis/pom.xml
java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml

Release java client 5.0.2

---

java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageIdCodec.java

Fix the time zone to generate message id

---

.asf.yaml

Follow the main repo: https://github.com/apache/rocketmq/pull/5341

Update asf.yaml to modify the notifications

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/ClientMeter.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/ClientMeterManager.java

Bugfix: shutdown ClientMeterManager during the closing of producer/consumer

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/SubscriptionLoadBalancer.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/PublishingLoadBalancer.java

There is no need to generate index in constructor of load balancer.

Define index of LoadBalancer as static

---

java/client-apis/src/main/java/org/apache/rocketmq/client/apis/message/Message.java
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/message/MessageBuilder.java
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/message/MessageView.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/GeneralMessage.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/GeneralMessageImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageBuilderImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageViewImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/PublishingMessageImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/message/GeneralMessageImplTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/message/MessageImplTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/tool/TestBase.java

Remove MessageBuilder#setTraceContext and MessageView#getTraceContext

---

golang/simple_consumer.go

golang: fix longpollingtimeout

---

golang/rpc_client.go
golang/simple_consumer.go

golang: add more log for debug level

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientSessionImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/ClientSessionImplTest.java

Bugfix: ClientSessionImpl#syncSettings should not block asynchronous worker thread

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java

Remove shutdown hook

---

golang/loadBalancer.go

fix isolated endpoints in LoadBalancer

golang: fix isolated endpoints in LoadBalancer

---

golang/simple_consumer.go

feat: fixed subscriptionExpressionsLock use

feat: fixed subscriptionExpressionsLock use

---

golang/simple_consumer.go

golang: fix Subscribe bug

---

golang/client.go

fix telemeter logic:
remove the registration of accessPoint

golang: fix telemeter logic

---

java/pom.xml

Bump maven-enforcer-plugin to 3.2.1

---

golang/message.go

golang: add 'AddProperty'

---

.github/workflows/build.yml
.github/workflows/rust_build.yml
rust/build.rs

Fix rust build

---

rust/Cargo.toml
rust/src/models/message.rs
rust/src/models/message_id.rs
rust/src/models/message_view.rs
rust/src/models/mod.rs

add some basic model ,like message id, message view,message

feat: add some basic message model(id,view,message)

---

golang/client_manager.go

golang: remove completed TODO

---

java/README.md

doc(rust): fix README.md of java sdk

---

.github/workflows/rust_build.yml

Reverts apache/rocketmq-clients#494

Revert "Remove clippy for testing"

---

.asf.yaml

Merging code in the protected branch requires mandatory approval from code review

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement_request.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

Add templates of issue and pull request

---

golang/rpc_client.go

[Fix] Lock not released correctly

---

.github/workflows/python_build.yml

Initial support for Python CI pipeline

---

.github/workflows/cpp_build.yml
README-CN.md
README.md
cpp/README.md
csharp/README-CN.md
csharp/README.md
golang/README.md
java/README-CN.md
java/README.md
rust/README.md

Fixes #519 
The badges for each language are not displaying the correct build status currently.

Fix the outdated badge

---

python/rocketmq/rpc_client.py

complete stream rpc function receiveMessages & telemetry. 
Add partial unit test

complete stream rpc function & rpc_client_mock

---

.github/workflows/build.yml

Fixes #535 
Aggregate the build results of the Python client in build.yml
N/A

Aggregate the build results of the Python client in build.yml

---

java/pom.xml

Fixes #549 
Since rocketmq-proto 2.0.3 is released, Let's bump rocketmq-proto from 2.0.2 to 2.0.3
N/A

Bump rocketmq-proto from 2.0.2 to 2.0.3

---

java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncSimpleConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerSingleton.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/PushConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

Fixes #551 
Add comments to turn off SSL into the example code to avoid some compatibility issues.
Just add comments, no need more testings.

Add comments to turn off SSL into the example code to avoid some compatibility issues

---

rust/examples/delay_producer.rs
rust/examples/fifo_producer.rs
rust/examples/producer.rs
rust/examples/simple_consumer.rs
rust/examples/transaction_producer.rs
rust/src/client.rs
rust/src/conf.rs
rust/src/producer.rs
rust/src/session.rs
rust/src/simple_consumer.rs

[ISSUE #575] Gracefully shutdown for Rust client

---

csharp/rocketmq-client-csharp/Signature.cs

csharp: Add using to wrap HMACSHA1 instance

---

rust/Cargo.toml

change the version of rust client from 5.0.0-rc1 to 5.0.0

release rust client 5.0.0

---

golang/client.go

optimize the logic of obtaining routing tasks

golang: optimize the logic of obtaining routing tasks

---

golang/rpc_client.go

Golang: change log output location

---

cpp/proto/apache/rocketmq/v2/service.proto
docs/workflow.md
golang/client.go
php/grpc/Apache/Rocketmq/V2/AdminClient.php
php/grpc/Apache/Rocketmq/V2/Publishing.php
php/protocol/apache/rocketmq/v2/service.proto

Golang: fix goroutine leak issue

---

.asf.yaml

Update .asf.yaml to enable merge java_release_5.0.6

---

java/client-apis/pom.xml
java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml

Java release 5.0.6

---

csharp/rocketmq-client-csharp/Utilities.cs

Just optimize performance.
Conducting benchmark tests on the previous and current methods using Benchmark, the speed has increased nearly threefold, and memory usage has also been reduced by 50%.
| Method       | Mean     | Error   | StdDev  | Gen0   | Allocated |
|------------- |---------:|--------:|--------:|-------:|----------:|
| AfterGetMd5  | 162.7 ns | 0.47 ns | 0.44 ns | 0.0095 |     168 B |
| AfterGetSha1 | 151.9 ns | 0.34 ns | 0.30 ns | 0.0114 |     200 B |
| GetMd5       | 468.8 ns | 1.25 ns | 1.17 ns | 0.0238 |     416 B |
| GetSha1      | 510.4 ns | 1.35 ns | 1.26 ns | 0.0267 |     472 B |
Existing unit tests cover these changes.

csharp: Optimize the performance of the Hash algorithm and reduce allocations.

---

rust/src/client.rs

…o query route from remote
In current implementation, the route is updated each time after querying remote queues. This will cause the index to be reset to zero that some queues won't be selected for polling or sending messages if the route is updated frequently. And in case of failure route requests, the route would be removed instead of being kept for availability.
The commit fixed these two issues above.
add 2 test cases.

[rust] check route equality and keep existing route in case of failure

---

golang/client.go
golang/client_test.go
golang/metadata/metadata.go
golang/producer.go
golang/publishing_message.go
golang/publishing_message_test.go
golang/simple_consumer.go
golang/simple_consumer_options.go
golang/transaction.go

Add namespace in Resource and metadata

golang: Add namespace in Resource and metadata

---

csharp/rocketmq-client-csharp/MessageView.cs
csharp/rocketmq-client-csharp/Utilities.cs

使用.net5中的新方法减少分配，优化性能

---

.github/workflows/codespell_check.yaml

Force set code spell plugin version to 2.1.0

---

java/client-apis/pom.xml
java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml
java/test/pom.xml

[maven-release-plugin] prepare release java-5.0.7

---

java/client-apis/pom.xml
java/client-shade/pom.xml
java/client/pom.xml
java/pom.xml
java/test/pom.xml

[maven-release-plugin] prepare for next development iteration

---

golang/client.go
golang/client_manager.go

https://github.com/apache/rocketmq-clients/issues/739

Remove useless heartbeat success log prints

---

python/rocketmq/signature.py
python/rocketmq/simple_subscription_settings.py

[ISSUE #784] fix python client 

---

.github/workflows/csharp_build.yml
csharp/examples/examples.csproj
csharp/rocketmq-client-csharp/Client.cs
csharp/rocketmq-client-csharp/ClientManager.cs
csharp/rocketmq-client-csharp/Session.cs
csharp/rocketmq-client-csharp/Signature.cs
csharp/rocketmq-client-csharp/rocketmq-client-csharp.csproj
csharp/tests/tests.csproj

[csharp] update TFM to net6 and net8

---

csharp/rocketmq-client-csharp/rocketmq-client-csharp.csproj

Release C# client 5.2.0

---

.github/workflows/java_build.yml
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/ProducerImpl.java

[ISSUE #825] Jave client TransactionProducer send need retry

---

java/client-shade/pom.xml
java/client/pom.xml
java/client/src/main/java/org/apache/rocketmq/client/java/exception/PayloadEmptyException.java
java/client/src/main/java/org/apache/rocketmq/client/java/exception/StatusChecker.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageBuilderImpl.java
java/pom.xml

[ISSUE #858] Jave client validate Message Body to avoid setting empty Body.

---

nodejs/src/client/BaseClient.ts

[ISSUE #8870] Correct reported language code in nodejs client

---

.github/workflows/java_coverage.yml
README-CN.md
README.md
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/producer/Producer.java
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/producer/RecallReceipt.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManager.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManagerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/ProducerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/RecallReceiptImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/SendReceiptImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClient.java
java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClientImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/ClientManagerImplTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/producer/ProducerImplTest.java

[ISSUE #878] The java implementation of recalling API

---

.github/workflows/python_build.yml
python/example/async_producer_example.py
python/example/async_simple_consumer_example.py
python/example/normal_producer_example.py
python/example/simple_consumer_example.py
python/example/transaction_producer_example.py
python/rocketmq/v5/client/client.py
python/rocketmq/v5/client/client_configuration.py
python/rocketmq/v5/consumer/simple_consumer.py
python/rocketmq/v5/model/message.py
python/rocketmq/v5/util/message_id_codec.py
python/rocketmq/v5/util/misc.py
python/rocketmq/v5/util/signature.py
python/setup.py

1. Fix the bug related to message ID length
2. Fix the bug which sync the subscription relationship without expression
3. The subscribe method adds raise exception
4. Set default values for AK and SK with empty strings

python sdk 5.0.2

---

README-CN.md
README.md

[ISSUE #914] Update C# feature description in README.md and README-CN.md

---

.github/workflows/csharp_build.yml

[ISSUE #922] Update GitHub workflows for C# client

---

csharp/rocketmq-client-csharp/Error/PayloadEmptyException.cs
csharp/rocketmq-client-csharp/Message.cs
csharp/rocketmq-client-csharp/StatusChecker.cs

[ISSUE #916] Add message body empty check for C# client

---

csharp/rocketmq-client-csharp/Producer.cs

[ISSUE #919] Add transaction message retry attempt for C# client producer

---

csharp/rocketmq-client-csharp/ClientManager.cs
csharp/rocketmq-client-csharp/IClientManager.cs
csharp/rocketmq-client-csharp/IRecallReceipt.cs
csharp/rocketmq-client-csharp/IRpcClient.cs
csharp/rocketmq-client-csharp/Producer.cs
csharp/rocketmq-client-csharp/RecallReceipt.cs
csharp/rocketmq-client-csharp/RpcClient.cs
csharp/rocketmq-client-csharp/SendReceipt.cs
csharp/tests/ClientManagerTest.cs
csharp/tests/ProducerTest.cs

[ISSUE #891] Implement message recalling API in C# SDK

---

cpp/examples/ExampleSimpleConsumer.cpp
cpp/proto/apache/rocketmq/v2/definition.proto
cpp/proto/apache/rocketmq/v2/service.proto
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/TelemetryBidiReactor.cpp
cpp/source/rocketmq/ClientImpl.cpp
cpp/source/rocketmq/SimpleConsumer.cpp
cpp/source/rocketmq/SimpleConsumerImpl.cpp

[ISSUE #928] Fix C++ simple consumer error code and close function

---

cpp/examples/ExampleFifoProducer.cpp
cpp/source/rocketmq/AsyncReceiveMessageCallback.cpp
cpp/source/rocketmq/SimpleConsumerImpl.cpp

[ISSUE #928] Fix C++ push consumer handle error code and change demo log level

---

python/rocketmq/v5/client/balancer/queue_selector.py
python/rocketmq/v5/client/client.py
python/rocketmq/v5/client/client_configuration.py
python/rocketmq/v5/client/connection/rpc_channel.py
python/rocketmq/v5/client/connection/rpc_client.py
python/rocketmq/v5/client/metrics/client_metrics.py
python/rocketmq/v5/consumer/simple_consumer.py
python/rocketmq/v5/exception/client_exception.py
python/rocketmq/v5/log/log_config.py
python/rocketmq/v5/model/callback_result.py
python/rocketmq/v5/model/filter_expression.py
python/rocketmq/v5/model/message.py
python/rocketmq/v5/model/metrics.py
python/rocketmq/v5/model/send_receipt.py
python/rocketmq/v5/model/topic_route.py
python/rocketmq/v5/producer/producer.py
python/rocketmq/v5/test/test_base.py
python/rocketmq/v5/test/test_consumer.py
python/rocketmq/v5/test/test_producer.py
python/rocketmq/v5/util/client_id.py
python/rocketmq/v5/util/message_id_codec.py
python/rocketmq/v5/util/messaging_result_checker.py
python/rocketmq/v5/util/misc.py
python/rocketmq/v5/util/signature.py
python/setup.py

1、Fixed some exceptions when integrating with other asynchronous frameworks.
2、Fix bug where request timeout in the configuration is not take effect.

python 5.0.3

---

cpp/examples/ExampleSimpleConsumer.cpp
cpp/include/rocketmq/SimpleConsumer.h
cpp/source/rocketmq/SimpleConsumer.cpp

[ISSUE #935] C++ simple consumer should remove destructor

---

golang/message.go
golang/pkg/utils/utils.go
golang/pkg/utils/utils_test.go

Added support for zlib compression format

golang: Added support for zlib compression format

---

nodejs/src/client/BaseClient.ts

change lan to http 

---

java/client/pom.xml
java/client/src/main/java/org/apache/rocketmq/client/java/message/MessageViewImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/misc/Utilities.java
java/client/src/test/java/org/apache/rocketmq/client/java/misc/UtilitiesTest.java
java/pom.xml

[ISSUE #959] Automatically select the appropriate decompression algorithm according to magic code

---

.github/workflows/csharp_build.yml
csharp/rocketmq-client-csharp/MessageView.cs
csharp/rocketmq-client-csharp/Utilities.cs

Fixes #954 
Add ZLib decompression support in C# client
N/A

[ISSUE #954] Add ZLib decompression support in C# client

---

.github/workflows/build.yml

Use script to check changed files instead for dorny/paths-filter@v2 in action workflows.

Use script to check changed files instead for dorny/paths-filter@v2 in action workflows.

---

.github/workflows/java_build.yml
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/consumer/PushConsumerBuilder.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/FifoConsumeService.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerBuilderImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerImpl.java
java/test/src/test/java/org/apache/rocketmq/test/client/AttemptIdIntegrationTest.java
java/test/src/test/java/org/apache/rocketmq/test/client/FifoConsumeAcceleratorTest.java
java/test/src/test/java/org/apache/rocketmq/test/server/BaseMockServerImpl.java
java/test/src/test/java/org/apache/rocketmq/test/server/GrpcServerIntegrationTest.java
java/test/src/test/java/org/apache/rocketmq/test/server/MockServer.java

[ISSUE #984] Support fifo parallel consume in java pushconsumer 

---

.github/workflows/cpp_build.yml
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/TelemetryBidiReactor.cpp
cpp/source/client/include/TelemetryBidiReactor.h
cpp/source/rocketmq/ClientImpl.cpp
cpp/source/rocketmq/ConsumeMessageServiceImpl.cpp
cpp/source/rocketmq/ProducerImpl.cpp
cpp/source/rocketmq/PushConsumerImpl.cpp
cpp/source/rocketmq/include/ConsumeMessageServiceImpl.h

[ISSUE #1001] C++ client should block on build when sync settings failed

---

README-CN.md
README.md
cpp/include/rocketmq/PushConsumer.h
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/include/ClientConfig.h
cpp/source/rocketmq/ConsumeMessageServiceImpl.cpp
cpp/source/rocketmq/PushConsumer.cpp
cpp/source/rocketmq/PushConsumerImpl.cpp
cpp/source/rocketmq/include/ClientImpl.h
cpp/source/rocketmq/include/SimpleConsumerImpl.h

[ISSUE #984] [C++] Support fifo parallel consume in C++ PushConsumer

---

golang/consumer_service.go

golang: remove debug log

---

golang/push_consumer.go

compatible with some abnormal scenarios, such as flowlimit

golang: compatible with some abnormal scenarios, such as flowlimit

---

.github/workflows/cpp_build.yml
cpp/examples/ExampleSimpleConsumer.cpp
cpp/include/rocketmq/SimpleConsumer.h
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/include/ClientManager.h
cpp/source/client/include/ClientManagerImpl.h
cpp/source/rocketmq/PushConsumerImpl.cpp
cpp/source/rocketmq/SimpleConsumer.cpp
cpp/source/rocketmq/SimpleConsumerImpl.cpp
cpp/source/rocketmq/include/SimpleConsumerImpl.h

Support continuous visibility timeout adjustment for SimpleConsumer
Fixes #1035

[ISSUE #1035] [C++] Support continuous visibility timeout adjustment for SimpleConsumer

---

.github/workflows/rust_build.yml
.github/workflows/rust_coverage.yaml

[Rust] Fix Github Rust Workflow

---

golang/client.go
golang/producer.go
golang/protocol/v2/service.pb.go
golang/push_consumer.go
golang/simple_consumer.go

Fixes https://github.com/apache/rocketmq-clients/issues/1026
refer to https://github.com/apache/rocketmq-clients/pull/1018 Modify the go version，realize #https://github.com/apache/rocketmq-clients/issues/1075

[ISSUE #1075] [Golang] Support ReconnectEndpointsCommand
