java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManager.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManagerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClient.java
java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClientImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImplTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/tool/TestBase.java

Bugfix: blocking message receiveing may exhausts all async worker threads

---

golang/client.go
golang/client_test.go
golang/config.go
golang/example/consumer/simple_consumer/main.go
golang/example/producer/async/main.go
golang/example/producer/delay/main.go
golang/example/producer/fifo/main.go
golang/example/producer/normal/main.go
golang/example/producer/transaction/main.go
golang/producer_test.go
golang/simple_consumer.go

1. remove redundant configuration
2. added configuration check before simpleConsumer starts

golang: remove redundant configuration

---

java/client/src/main/java/org/apache/rocketmq/client/java/message/PublishingMessageImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/message/PublishingMessageImplTest.java

Since OpenTelemetry community recommended to propagate trace context through message properties rather than the existing `trace_context` field, and the implementation of `PublishingMessageImpl#getProperties` made a deep copy, making it impossible to update the message properties in `PublishingMessageImpl`, an independent method should be added for propagating trace context through `PublishingMessageImpl`.

Add extraProperties for PublishingMessageImpl

---

golang/producer.go
golang/simple_consumer.go

The original option is not isolated, so the producer and consumer instances can only be initialized in sequence on the main thread

golang: fix options bug

---

golang/client.go
golang/client_manager_test.go
golang/client_test.go
golang/producer_test.go
golang/simple_consumer.go

golang: fast to the ok state

---

golang/simple_consumer.go

Add error handling in simple consumer in golang for Subscribe and Unsubscribe when getting available message queue from server

golang: add error handling in simple consumer

---

golang/error.go

#349 
fix ErrRpcStatus.GetCode() stack overflow

golang: fix ErrRpcStatus.GetCode() stack overflow

---

java/client-apis/src/main/java/org/apache/rocketmq/client/apis/ClientConfiguration.java
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/ClientConfigurationBuilder.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/Client.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManagerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/metrics/ClientMeterManager.java
java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClientImpl.java

Allow user to disable TLS

---

java/client-shade/src/main/resources/rocketmq.logback.xml
java/client/src/main/resources/logback.xml

Add AsyncAppender support

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/SimpleConsumerImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImplTest.java
java/pom.xml

Bump rocketmq-proto to 2.0.2

---

.gitignore
golang/.gitignore
golang/client.go
golang/client_manager.go
golang/client_manager_test.go
golang/client_test.go
golang/rpc_client_mock.go

I'm trying to solve the issue described by @guyinyou in #182 
The new flow of execution after transmission error looks as follows:
- we encounter a server TelemetryCommand transmission error
- we set the state of recovery to true and skip to the next loop iteration
- if there is a transmission error when we are in recovery we release the observer and set the state of recovery to false
- if we manage to read the message we check if each of the servers is healthy, if not we release the observer and set the state of recovery to false
- if we managed to read the message and each server is healthy we process the message and set the state of recovery to false. 
I'm going to write the unit tests for this next.

try to recover on server TelemetryCommand transmission error

---

.github/workflows/golang_build.yml
.gitignore
golang/client.go
golang/client_manager_test.go
golang/client_test.go
golang/rpc_client.go
golang/simple_consumer.go

Currently the tests for recovering after TelemetryCommand transmission failure wait 3 seconds after the initial setup for the telemetry client goroutine to run. This is at the edge of expected wait time for the goroutine to go through all of the required code. Increasing the wait time for five seconds guarantees that by the time that we check the expected logs all of the testing scenario will have already completed. 
Fixes #410

Fix: increase wait time in recovery tests to avoid flaking

---

.github/workflows/java_build.yml

Ensure the compatibility of modifications to the RocketMQ Java client code with OpenTelemetry instrumentation

---

rust/proto/apache/rocketmq/v2/definition.proto
rust/proto/apache/rocketmq/v2/service.proto

[ISSUE #448] Update api proto for rust client

---

rust/Cargo.toml
rust/src/client.rs
rust/src/lib.rs
rust/src/model.rs
rust/src/producer.rs
rust/src/session.rs

fix: Fix Rust clippy warnings

---

golang/pkg/utils/utils.go
golang/pkg/utils/utils_test.go

fix: fix endpoints parsing in Go Client

---

rust/Cargo.toml
rust/README.md
rust/build.rs
rust/examples/producer.rs
rust/examples/simple_consumer.rs
rust/src/client.rs
rust/src/conf.rs
rust/src/error.rs
rust/src/lib.rs
rust/src/log.rs
rust/src/model/common.rs
rust/src/model/message.rs
rust/src/model/mod.rs
rust/src/producer.rs
rust/src/session.rs
rust/src/simple_consumer.rs
rust/src/util.rs

close #475 
Brief changelog:
1. implement heartbeat and telemetry rpc for both producer and simple consumer
2. implement receive and ack message rpc for simple consumer
3. add util module to abstract common functions
4. add simple consumer example and some tests

feat(rust): implement simple consumer

---

rust/README.md
rust/src/client.rs
rust/src/conf.rs
rust/src/error.rs
rust/src/lib.rs
rust/src/model/common.rs
rust/src/model/message.rs
rust/src/producer.rs
rust/src/session.rs
rust/src/simple_consumer.rs
rust/src/util.rs

We achieved 86.75% unit test coverage using llvm-cov. Please see the attached test report for details.

test(rust): add unit tests

---

.github/workflows/rust_build.yml

Using clippy component of installed Rust toolchain as the lint tool directly in GitHub Action workflow

---

README-CN.md
README.md

Add PHP part in 'Features and Status' of README.md

---

csharp/rocketmq-client-csharp/Utilities.cs
csharp/tests/UtilitiesTest.cs

Fixes #514 
Utilities#GetMacAddress() may return null in some situations.
Unit testing.

Return valid MAC address in any situation

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java

This modification is trivial, so I didn't create an issue.
When build `AckMessageRequest` in `wrapAckMessageRequest()` ` setGroup()` has been invoked twice, which is unnecessary.
no need

fix: setGroup() invoked twice when wrapAckMessageRequest()

---

.gitignore
python/README-CN.md
python/README.md

Fixes #523 
Add virtual environment configuration part into Python README.md
N/A

Add virtual environment configuration part into Python README.md

---

.github/workflows/rust_build.yml
rust/.cargo/Cargo.lock.min
rust/.cargo/config.toml
rust/Cargo.toml
rust/src/client.rs
rust/src/conf.rs
rust/src/session.rs

[ISSUE #526] feat(rust): support ak/sk authorization

---

python/rocketmq/client_config.py
python/rocketmq/client_id_encoder.py
python/rocketmq/client_manager.py
python/rocketmq/log.py
python/rocketmq/message.py
python/rocketmq/message_id.py
python/rocketmq/send_receipt.py
python/rocketmq/signature.py
python/rocketmq/utils.py

Implement a series of features
1. Encoder for client id
2. Enrich the logging information
3. Implement authentication algorithm
4. Add other basic data structures

Implement a series of features

---

java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncProducerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncSimpleConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerDelayMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerFifoMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerNormalMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerSingleton.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerTransactionMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/PushConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/SimpleConsumerExample.java

Fixes #539 
Provides singleton example for producer.
No testing needed.

Provides singleton example for producer

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImplTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImplTest.java

Fixes #525 
Set the `attempt_id` for `ReceiveMessageRequest` of the push consumer, and reuse the last `attempt_id` when the request times out.
By unit testing.

Implement the reentrant PushConsumer message receiving

---

README-CN.md
README.md
rust/.cargo/Cargo.lock.min
rust/Cargo.toml
rust/examples/delay_producer.rs
rust/examples/fifo_producer.rs
rust/examples/producer.rs
rust/examples/simple_consumer.rs
rust/examples/transaction_producer.rs
rust/src/client.rs
rust/src/conf.rs
rust/src/lib.rs
rust/src/model/message.rs
rust/src/model/mod.rs
rust/src/model/transaction.rs
rust/src/producer.rs
rust/src/session.rs
rust/src/simple_consumer.rs

[ISSUE #555] Support transaction message for Rust SDK

---

rust/.cargo/Cargo.lock.min
rust/Cargo.toml
rust/src/util.rs

[ISSUE #557] fix(rust): change dependency from os_type to os_info

---

rust/README.md
rust/examples/transaction_producer.rs
rust/src/client.rs
rust/src/model/transaction.rs
rust/src/producer.rs
rust/src/simple_consumer.rs

[ISSUE #563] Optimize example and doc for Rust SDK

---

.github/workflows/cpp_build.yml

Fixes #569 
This change only affects the Bazel build in the CI and makes the CI green again. Because of an update of Visual Studio the Bazel Windows Build is failing - more details here: https://github.com/bazelbuild/bazel/issues/18592
One workaround is to use VS 2019 for now, until this is fixed. Another option would be to modify the directory of VS2022. Once this is fixed the Bazel Windows CI build will switch back to VS2022.

Switch back to VS2019 for passing the cpp build

---

cpp/examples/ExampleProducer.cpp
cpp/examples/ExampleProducerWithAsync.cpp
cpp/examples/ExampleProducerWithFifoMessage.cpp
cpp/examples/ExampleProducerWithTimedMessage.cpp
cpp/examples/ExampleProducerWithTransactionalMessage.cpp
cpp/examples/ExamplePushConsumer.cpp
cpp/examples/ExampleSimpleConsumer.cpp
cpp/include/rocketmq/Configuration.h
cpp/source/base/Configuration.cpp
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/include/ClientConfig.h
cpp/source/client/include/ClientManagerImpl.h
cpp/source/rocketmq/ClientImpl.cpp
cpp/source/rocketmq/Producer.cpp
cpp/source/rocketmq/PushConsumer.cpp
cpp/source/rocketmq/SimpleConsumer.cpp
cpp/source/rocketmq/include/ClientImpl.h
cpp/source/rocketmq/include/SimpleConsumerImpl.h

Allow user to disable TLS in cpp.

Allow user to disable TLS in cpp.

---

.github/workflows/cpp_build.yml
.github/workflows/csharp_build.yml
.github/workflows/golang_build.yml
.github/workflows/java_build.yml
.github/workflows/php_build.yml
.github/workflows/rust_build.yml

Fixes #570 
By default, the GitHub Actions matrix strategy enables a "fail-fast" mechanism, which leads to some build results in specific environments being invisible to us due to the cancellation of remaining tasks when any task fails. We hope to disable this "fail-fast" feature so that we can see the complete build results, as the remaining tasks will be allowed to continue running even if a task fails.
No need testings.

Disable fail fast for GitHub Action matrix

---

python/rocketmq/client.py
python/rocketmq/client_config.py
python/rocketmq/client_id_encoder.py
python/rocketmq/definition.py
python/rocketmq/exponential_backoff_retry_policy.py
python/rocketmq/producer.py
python/rocketmq/publish_settings.py
python/rocketmq/publishing_message.py
python/rocketmq/rpc_client.py
python/rocketmq/send_receipt.py
python/rocketmq/session.py
python/rocketmq/status_checker.py
python/rocketmq/utils.py
python/tests/test_foo.py

**Regular heartbeat**
done
**Telemetry performs abnormal recovery**
done
**The retry of message sending**
done
**Failed node isolation**
done
**transaction & delay & fifo message**
done
run 4 tests in producer.py & test heartbeat & telemetry rebuild by hands

General message engineering in Producer

---

docs/design.md
docs/workflow.md

1. The client identifier "macbook-pro@90009@0@2dyeb8lep" can be divided into four parts using the separator "@".Among these parts, the client index within the current process should be 0.
2. The sentence "Check the cache is full, consumer will try to receive message immediately, otherwise retry after 1 second" is expressed incorrectly. It should be stated that when the cache is full, the consumer should retry after 1 second.

fix(doc): correct incorrect statements in Design and Workflow sections

---

python/examples/simple_consumer_example.py
python/rocketmq/client.py
python/rocketmq/consumer.py
python/rocketmq/definition.py
python/rocketmq/filter_expression.py
python/rocketmq/message.py
python/rocketmq/producer.py
python/rocketmq/rpc_client.py
python/rocketmq/simple_consumer.py
python/rocketmq/simple_subscription_settings.py
python/rocketmq/state.py

implement simple consumer for python client
now it can start first, and then receive message, finally it can send ack to server.
use test function in simple_consumer.py to test the simple consumer

Implementation of Simple Consumer for Python Client

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumeTask.java

Fixes #608
Print message id and message queue when consume result is failure to provide more information.

[ISSUE #608] Print message id and message queue when consume result is failure

---

cpp/proto/apache/rocketmq/v2/service.proto
cpp/third_party/opencensus/0.5.0-alpha/opencensus/stats/internal/stats_manager.h
docs/workflow.md
php/grpc/Apache/Rocketmq/V2/AdminClient.php
php/grpc/Apache/Rocketmq/V2/MessagingServiceClient.php
php/grpc/Apache/Rocketmq/V2/Publishing.php
php/protocol/apache/rocketmq/v2/service.proto
python/README.md

In the doc for python client there is a broken url here
https://github.com/apache/rocketmq-clients/blob/92c627d55af415a5597ee9ea0efff27c313582b5/python/README.md?plain=1#L9
The problem is that the url is repeated twice.
Not needed

python: doc mistake fixed

---

cpp/source/rocketmq/ConsumeMessageServiceImpl.cpp
cpp/source/rocketmq/include/ConsumeMessageServiceImpl.h
cpp/source/rocketmq/tests/BUILD.bazel
cpp/source/rocketmq/tests/ConsumeMessageServiceTest.cpp

…tdown lifecycle management
fix #521 

Sync state of consume-message-service according to start/shutdown lifecycle management

---

cpp/examples/ExampleProducerWithTimedMessage.cpp
cpp/source/rocketmq/ProducerImpl.cpp

Fix the method of setting timestamp for Delay Producer. Before fixing, it may appear that the Message Type cannot be recognized as DELAY by the server, but rather as NORMAL.

Fix cpp delay Producer

---

cpp/examples/ExampleProducer.cpp
cpp/examples/ExampleProducerWithAsync.cpp
cpp/examples/ExampleProducerWithFifoMessage.cpp

Add `withTopics` in cpp examples.
If this is not enabled, it will cause the connection between the client and the server to fail.

Polish the cpp examples

---

rust/Cargo.toml
rust/examples/producer.rs
rust/examples/simple_consumer.rs
rust/src/client.rs
rust/src/model/common.rs
rust/src/model/message.rs
rust/src/model/transaction.rs
rust/src/session.rs
rust/src/simple_consumer.rs
rust/src/util.rs

Brief changelog for rust client:
1. Support changing invisible duration RPC
2. Suppress the warning about no settings telemetry command handler

feat(rust): support changing invisible duration

---

java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncProducerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/AsyncSimpleConsumerExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerDelayMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerFifoMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerNormalMessageExample.java
java/client/src/main/java/org/apache/rocketmq/client/java/example/ProducerTransactionMessageExample.java

no issue related
1. java client producer examples have some out-of-date comments;
2. add maxPollingSize limit in AsyncSimpleConsumerExample, to avoid "polling full" error.
no need to test

update out-of-date java client examples

---

rust/Cargo.toml
rust/examples/transaction_producer.rs
rust/src/client.rs
rust/src/util.rs

lazy_static is almost inactive, most of the projects in the rust community use once_cell instead of lazy_static, while once_cell's performance is  [a little bit more](https://github.com/matklad/once_cell/tree/master/examples) and the development is active.
1. remove lazy_static dependency
2. upgrade once_cell

Replace lazy_static with once_cell

---

cpp/.gitignore
cpp/source/rocketmq/Producer.cpp
cpp/source/rocketmq/ProducerImpl.cpp
cpp/source/rocketmq/PushConsumerImpl.cpp
cpp/source/rocketmq/SimpleConsumerImpl.cpp
cpp/source/rocketmq/include/ClientImpl.h
cpp/source/rocketmq/include/ProducerImpl.h
cpp/source/rocketmq/include/PushConsumerImpl.h
cpp/source/rocketmq/include/SimpleConsumerImpl.h

fix #639 
Fix semantics of topicOfInterest, which should be a reader

fix #639 fix semantics of topicOfInterest

---

java/client-apis/src/main/java/org/apache/rocketmq/client/apis/ClientConfiguration.java
java/client-apis/src/main/java/org/apache/rocketmq/client/apis/ClientConfigurationBuilder.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/Settings.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushSubscriptionSettings.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/SimpleConsumerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/SimpleSubscriptionSettings.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/ProducerImpl.java
java/client/src/main/java/org/apache/rocketmq/client/java/impl/producer/PublishingSettings.java
java/client/src/main/java/org/apache/rocketmq/client/java/message/PublishingMessageImpl.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/PushSubscriptionSettingsTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/impl/consumer/SimpleSubscriptionSettingsTest.java
java/client/src/test/java/org/apache/rocketmq/client/java/tool/TestBase.java

Fixes #660
Add namespace in java client

[ISSUE #660] Add namespace in java client

---

java/client/src/main/java/org/apache/rocketmq/client/java/rpc/Signature.java

Add namespace in metadata
Fixes #660
Add namespace in metadata

[ISSUE #660] Add namespace in metadata

---

rust/src/error.rs
rust/src/model/message.rs
rust/src/producer.rs

The rust client doesn't have feature of checking message type with topic type. This pull request is to implement it.
I've modified test cases in producer.rs to ensure tests to pass. Those tests are quite sufficient to test this feature.

[rust]support message type check on rust client

---

nodejs/src/client/BaseClient.ts

fix(nodejs): send heart beats every 10 seconds

---

rust/Cargo.toml
rust/src/client.rs
rust/src/producer.rs
rust/src/simple_consumer.rs

Fixes #634 
Fixes #598
I've refactored the way of processing telemetry commands. Now the transaction command from the server is processed in Producer instead of Client.  The client with different types can handle telemetry command within its own impl block.
run cargo test and example to make sure it works

[rust] support handling settings command in Producer

---

golang/client.go
golang/client_test.go
golang/loadBalancer.go

Fixes #679 
1. correct judgment of topic route equality
2. do not reset index when update loadBalancer

[ISSUE #679] Fix judgment of topic route equality and optimize loadBalancer

---

rust/src/client.rs
rust/src/conf.rs
rust/src/model/transaction.rs
rust/src/producer.rs
rust/src/session.rs
rust/src/simple_consumer.rs
rust/src/util.rs

To align with Java implementations, the rust client should synchronize client settings per 30 seconds by default.

[rust]sync client settings periodically

---

csharp/rocketmq-client-csharp/Utilities.cs
csharp/tests/UtilitiesTest.cs

Fixes #702
获取地址时排除 ```NetworkInterfaceType``` 值为 ```53``` 的网卡，在返回时再次检测物理地址的长度是否小于要求长度(```6```)，如果小于，则返回 ```RandomMacAddressBytes```，如果大于，则返回物理地址。
更新相关联的单元测试，加入物理地址长度的检测。

修复获取网卡物理地址的问题

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/ProcessQueueImpl.java

[ISSUE #708] Fix the issue that PushConsumer reentrant pop doesn't work as expected

---

rust/src/client.rs

Now the client doesn't update topic route automatically that if topic configuration is updated on server there is no change for client to react on this change other than being restarted. In this PR, the client launches a scheduler to update the route of topics in route table.
I had run e2e test locally that everything is doing fine.

[rust]sync topic route every 30 seconds

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/ClientManagerImpl.java

Fixes #748 748
By using a bounded queue, a backpressure-like effect is achieved to avoid OOM (Out of Memory).

fixed #748

---

.github/workflows/cpp_build.yml
cpp/source/client/SessionImpl.cpp
cpp/source/client/TelemetryBidiReactor.cpp
cpp/source/client/include/TelemetryBidiReactor.h
cpp/source/stats/MetricBidiReactor.cpp
cpp/source/stats/OpencensusExporter.cpp
cpp/source/stats/include/MetricBidiReactor.h

Fixes #789 #790 #791 #792 #795 #796, and maybe #794 #797 .

Fix crash issue of TelemetryBidiReactor and MetricBidiReactor

---

python/rocketmq/message.py

解决非标准的gzip格式问题
在body_encoding == gzip 时, 使用了deflate压缩, 没有使用标准的gzip压缩, 故做了兼容, 防伪未来服务端修复这个bug

解决非标准的gzip压缩

---

java/client/src/main/java/org/apache/rocketmq/client/java/impl/consumer/PushConsumerImpl.java

[ISSUE #894] Make Client prefer to use endpoints in config when pick endpoints to QueryAssignments

---

.github/workflows/cpp_build.yml
cpp/.gitignore
cpp/examples/ExampleFifoProducer.cpp
cpp/examples/ExampleProducer.cpp
cpp/examples/ExampleProducerWithAsync.cpp
cpp/examples/ExampleProducerWithFifoMessage.cpp
cpp/examples/ExampleProducerWithTimedMessage.cpp
cpp/examples/ExampleProducerWithTransactionalMessage.cpp
cpp/examples/ExamplePushConsumer.cpp
cpp/examples/ExampleSimpleConsumer.cpp
cpp/source/base/include/InvocationContext.h
cpp/source/client/ClientManagerImpl.cpp
cpp/source/client/LogInterceptor.cpp
cpp/source/client/RpcClientImpl.cpp
cpp/source/client/SessionImpl.cpp
cpp/source/client/TelemetryBidiReactor.cpp
cpp/source/client/include/TopicRouteData.h
cpp/source/log/LoggerImpl.cpp
cpp/source/rocketmq/ClientImpl.cpp
cpp/source/rocketmq/ProducerImpl.cpp
cpp/source/rocketmq/include/ClientImpl.h
cpp/source/rocketmq/include/ProducerImpl.h

[ISSUE #928] [CPP] Fix some cpp client bug and make logs cleaner

---

cpp/examples/ExampleProducerWithTransactionalMessage.cpp
cpp/include/rocketmq/Producer.h
cpp/source/rocketmq/Producer.cpp
cpp/source/rocketmq/ProducerImpl.cpp
cpp/source/rocketmq/include/ProducerImpl.h

[ISSUE #934] C++ trans producer should return a SendReceipt object in the send call

---

golang/pkg/utils/utils.go
golang/pkg/utils/utils_test.go

Because the implementation of lz4 and zstd is an unofficial standard dependency. Remove support for lz4 and zstd compression algorithms

golang: Remove support for lz4 and zstd compression algorithms

---

.github/workflows/build.yml
java/README.md
rust/README.md

…ions.
use script to check changed files instead for dorny/paths-filter@v2 in action workflows.

Use script to check changed files instead for dorny/paths-filter@v2 in action workflows.

---

java/client/src/main/java/org/apache/rocketmq/client/java/rpc/RpcClientImpl.java

Change-Id: Ie14d6990373cb011da3f4c60aef3ca280ed63819
Fixes #872 
By default, the keep alive is not enabled. If the tcp has no response, without keep alive, it need longer time to find it broken.

[ISSUE #872] [Java] feat: should add default keepalive for grpc channel

---

golang/push_consumer.go
golang/simple_thread_pool.go

When pushconsumer is turned off, wait for messages that are already ready to be consumed

golang: when pushconsumer is turned off, wait for messages that are already ready to be consumed

---

java/pom.xml

Fixes #1051 
Logback version 1.3.15 is incompatible with SLF4J version 1.7.30.
The SLF4J version must be upgraded to 2.0.x.

[ISSUE #1051] Upgrade slf4j version to match current logback version

---

golang/simple_thread_pool.go

Fixes #1083
Triggering the judgment whether it is empty during task execution.
在触发执行任务的时候增加判空逻辑，防止收到管道关闭的信息误当作新任务。

[ISSUE #1083] [Golang] Fix start up failure problem
